### ISSUE TITLE
VS Installer install/update crashes on .NET 4.6.1 (CryptographicException - no SHA256 support)

### ISSUE THREAD

**Issue by jberezanski** [jberezanski/ChocolateyPackages#38]
The VS Installer OPC file (vs_installer.opc) uses SHA256 signatures now (since version 1.16.1243.427; previous version 1.15.3248.309 still used SHA1).

These signatures cannot be verified by unpatched .NET 4.6.1 due to lack of SHA256 support in PackageDigitalSignatureManager:

````
VisualStudio Bootstrapper:2018-05-07 20:25:54: Caught Exception: Type = CryptographicException, Message = SignatureDescription could not be created for the signature algorithm supplied., StackTrace =    w System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(X509Certificate2 certificate, Boolean verifySignatureOnly)
   at MS.Internal.IO.Packaging.XmlDigitalSignatureProcessor.Verify(X509Certificate2 signer)
   at System.IO.Packaging.PackageDigitalSignature.Verify(X509Certificate signingCertificate)
   at System.IO.Packaging.PackageDigitalSignatureManager.VerifySignatures(Boolean exitOnFailure)
   at Microsoft.VisualStudio.Setup.Bootstrapper.Opc.OpcVerifier.Verify(Stream packageStream, String layoutLocation)
   at Microsoft.VisualStudio.Setup.Bootstrapper.Bootstrapper.VerifyPackage(Stream packageStream)
````

Two possible solutions:
- install [May 2017 Cumulative Update for .NET 4.6.1](https://support.microsoft.com/en-us/help/4019114/security-and-quality-rollup-for-the-net-framework-3-5-service-pack-1-4) (or its security only variant), which adds SHA256 support to PackageDigitalSignatureManager
- update .NET dependency to 4.6.2 (contrary to [official requirements](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs))

**Comment by jberezanski** [comment]
Due to the multitude of KBs for different combinations of .NET and OS versions, patching .NET 4.6.1 would be a lot of work, packaging-wise. Let's simply update the dependency (Windows Update offers a newer .NET anyway).
